### ISSUE TITLE
Github Actions Deploy

### ISSUE THREAD

**Issue by realonbebeto** [saadpasta/developerFolio#611]
### Describe the bug

The bug is I can't build and deploy to gh-pages using github actions

### Steps to reproduce

1. Running the repo with github actions to deploy to gh-pages

### Expected behavior

it should run with github actions

### Is this responsiveness Issue

NO

### Screenshots

![1](https://user-images.githubusercontent.com/59011741/226678564-58e17256-78ff-4ce4-980e-ce9403c25b16.png)
![2](https://user-images.githubusercontent.com/59011741/226678576-150f3c83-58c5-4435-b2c9-fbe17a0a7862.png)
![3](https://user-images.githubusercontent.com/59011741/226678588-75fff654-9238-4f20-bd00-261ae94be9a6.png)
![4](https://user-images.githubusercontent.com/59011741/226678597-40847425-61c7-482e-ac24-9754a2645fc2.png)
![5](https://user-images.githubusercontent.com/59011741/226678605-31c2c57d-60ae-48fa-817c-a64704f635bf.png)
![6](https://user-images.githubusercontent.com/59011741/226678615-10b3caa8-b7d8-4a25-bfab-27ed6ec1fbe6.png)
![7](https://user-images.githubusercontent.com/59011741/226678629-ac2d5eb7-aa1c-4361-b014-f72ab6d565a8.png)
NO
![8](https://user-images.githubusercontent.com/59011741/226678634-a93730e6-a5cd-4fed-bc9e-ad4372694280.png)
N
![9](https://user-images.githubusercontent.com/59011741/226678645-7df3e14d-48e6-4ffe-a05d-871133158bd8.png)
![10](https://user-images.githubusercontent.com/59011741/226678658-3ccca787-9ac4-4da6-b177-0c3a099bfa9b.png)
no
![11](https://user-images.githubusercontent.com/59011741/226678665-bb702a08-9873-4181-bbe5-0beb44c83728.png)
![12](https://user-images.githubusercontent.com/59011741/226678672-1f8d9dd0-82e0-4ca9-8e6b-f3b6de38eedc.png)

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by FoxxMD** [comment]
In `deploy.yml` replace the job like so:

```yaml
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install and Build 🔧 # Build the Project
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
```
